### ISSUE TITLE
"TypeError: Cannot read property 'root' of undefined" ecstatic

### ISSUE THREAD

**Issue by vladikoff** [max-mapper/doorknob#2]
Hey, wanted to try this out with `node -v v0.10.13`, what am I missing?

```
$ npm test

> doorknob@0.2.0 test /Users/vlad/dev/doorknob
> browserify www/index.js -o www/bundle.js && node test.js


/Users/vlad/dev/doorknob/node_modules/ecstatic/lib/ecstatic.js:18
    dir = options.root;
                 ^
TypeError: Cannot read property 'root' of undefined
    at module.exports (/Users/vlad/dev/doorknob/node_modules/ecstatic/lib/ecstatic.js:18:18)
    at module.exports (/Users/vlad/dev/doorknob/server.js:14:23)
    at Object.<anonymous> (/Users/vlad/dev/doorknob/test.js:1:82)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

**Comment by max-mapper** [comment]
sorry, I changed it so you have to call .listen instead if it calling .listen for you but forgot to update the test. fixed now
